### ISSUE TITLE
Changes detection 

### ISSUE THREAD

**Issue by polc** [matthiasnoback/TalisORM#19]
Hello, I'm pretty confused with the handling of the child entities in TalisORM and would love some insight (if you have time). 

Particularity, to detect changes it just insert or update every children, so if I have an aggregate with 400 child entities, it will produce `800` queries for each save, isn't it a bit expensive? (maybe not)

Also the deletion of a child is a special case because I have to indicate in the aggregate when it happen, while it's a bit an hassle, maybe it's just because you consider it's doesn't happen so often? 

Some randoms thought in top of my head : 
* Usage of proxies for child entities may be used to keep track of creation and updates of child entities (meaning we hydrate them outside the aggregate).
* If a few more queries are not a problem, maybe deleting every child entities not in the aggregate would be enough (`DELETE FROM children WHERE id NOT in (:ids)`)
* Is it a multi-database ORM ? Focusing on PostgreSQL for example may allow to use JSON capabilities of the database to retrieve aggregate state and his child entities state in 1 query

Cheers!

**Comment by prohalexey** [comment]
Hello @polc ! I have same questions. And I tried to rewrite code but that is quite difficult. 

1. `:ids` are not scalar value(not always). 
Because of this we need to do one delete query for every child.

Let's say we have 2 children `[['a' => 1, 'b' => 2], ['a' => 2, 'b' =>1]]. `
We can't delete these children with one query which using IN statement. 
Query "DELETE FROM table WHERE a IN (1,2) AND b IN (2,1)" is wrong.
The correct query is "DELETE FROM table WHERE (a=1 AND b=2) OR (a=2 AND b=1) OR ...".
But this is a bad query. Highly likely that database will do a SEQ SCAN for DELETE operation.

2. Second question is why childEntity extends Entity which have a function 
`public static function identifierForQuery(AggregateId $aggregateId);`
How can I use this function ?

Maybe something like this ? 
_Pseudo code. Just wrote my thoughts._
```
public function delete(Aggregate $aggregate)
{
    $this->connection->transactional(function () use ($aggregate) {
        $this->connection->delete(
            $this->connection->quoteIdentifier($aggregate::tableName()),
            $aggregate->identifier()
        );

        foreach ($aggregate->childEntitiesByType() as $type => $childEntities) {
            $this->canBeMassDeleted($childEntities)
                ? $this->massDelete($childEntities)
                : $this->oneByOneDelete($childEntities);
        }
    });
}

private function canBeMassDeleted(&$childEntities)
{
    $childEntity = reset($childEntities);

    if ($childEntity && \count($childEntity::identifierForQuery(??? AggregateId ???)) === 1) {
        return true;
    }
    return false;
}

private function massDelete(&$childEntities)
{
    $values = [];
    $identifierKey = null;
    $tableName = null;

    /*
     * I think this is ugly, it will be better if we could get identifier's structure from childEntity
     */
    foreach ($childEntities as $childEntity) {
        /** @var ChildEntity $childEntity */
        foreach ($childEntity->identifier() as $key => $value) {
            if (null === $identifierKey || null === $tableName) {
                $identifierKey = $key;
                $tableName = $childEntity::tableName();
            }
            $values[] = $value;
        }
    }

    if ($tableName && $identifierKey && !empty($values)) {

        // But we can't do this. PDO and DOCTRINE has limitations

        $this->connection->delete(
            $this->connection->quoteIdentifier($tableName),
            $values
        );
    }
}

private function oneByOneDelete(&$childEntities)
{
    foreach ($childEntities as $childEntity) {
        /** @var ChildEntity $childEntity */
        $this->connection->delete(
            $this->connection->quoteIdentifier($childEntity::tableName()),
            $childEntity->identifier()
        );
    }
```

There are so many questions but the answers are so few

**Comment by prohalexey** [comment]
I think that we must divide storage identifier(will be better if it will be interger) for manipulations in the database, and unique identifier(may be composite and maybe with the unique constraint in the db) which will be used in the domain logic.

**Comment by matthiasnoback** [comment]
Hey, thanks for joining the discussion here. Your comments have led me to think some more about the whole change tracking thing.

I didn't want proxies, because you should be able load the whole aggregate at once. It shouldn't have that many parts anyway. "Keep your aggregates small", as the important aggregate design rule says. Which is also why this library shouldn't be adding a lot of queries. But you're right, there's no change/dirty tracking for fields, so even if nothing has changed, we still issue an UPDATE query for every child entity. But there shouldn't be hundreds anyway.

As pointed out, we can't easily do "mass deletes", since this library is designed to explicitly support multi-column primary keys. So if you'd like to do that, you'd have to invent some more parts, and I wanted to keep the interfaces as small as possible.

TalisORM is still based on relational databases. The idea behind it is pretty much traditional: mapping happens from field to column and back. Aggregates can simply be stored as documents in a non-relational database ("NoSQL"), like Postgres with JSON as you suggest.

About `identifierForQuery()` - it's used to find the child entities for a given aggregate.

Honestly, I don't think mass deletion will make a big difference. It's a micro-optimization. In fact, since `identifier()` should only return primary key values (this isn't documented yet), it'll probably not make a big difference. I didn't test that, but in the normal scenario it shouldn't result in a sequential scan.

**Comment by matthiasnoback** [comment]
Anyway! There's a big issue that I need to fix first. With the current setup, it's possible that we're updating an aggregate which should actually be created/inserted. It could happen that we create an object, persist it, then someone else did the same thing and the ID is already in use (and so we do an UPDATE instead of an INSERT). This is only true if the uniqueness of the identifier isn't guaranteed by the ID creation mechanism (i.e. use UUID, sequence, etc.).

**Comment by polc** [comment]
hey thanks for the insight! 

About the JSON capabilities, I was thinking about using the new json functions of PostgreSQL to create a JSON object well fit for hydrating my aggregate (like in https://dba.stackexchange.com/a/144156 for example). Focusing on PostgreSQL could also allow the ORM to do UPSERT queries. But It's kind of a micro optimization (but a fun one :D) ! 

I'm still not very happy with the deletion tracking because I feel like my aggregates have too much ORM boilerplate. But not a big deal IMO :p   

Also in a project which was not using UUIDs I had different methods  `create` and `update` to prevent concurrent ids, not sure it's applicable to TalisORM thought!

**Comment by matthiasnoback** [comment]
I'll probably be introducing something like an identity map, which may help with tracking deleted entities. I agree it's not ideal right now (but it's pragmatic!). The thing is, I'm constantly pushing to remove more magic, but I guess I have to re-add some.

**Comment by polc** [comment]
Thanks for the answers, very informative!

**Comment by matthiasnoback** [comment]
Thanks for joining the discussion, very helpful!
