### ISSUE TITLE
Implementation problem with "collection aggregates"

### ISSUE THREAD

**Issue by pl-github** [matthiasnoback/TalisORM#28]
Hi Matthias,

I am very excited about how easy it is to implement objects according to the DDD principles with TalisORM, with Doctrine workarounds are often necessary. I have migrated a small test project from a Doctrine implementation to TalisORM and encountered a difficulty (with Doctrine this was already a problem).

Here's some pseudo code I'm trying to use to describe the problem.

```
/**
 * Represents a product in a catalog.
 */
class Product
{
    /** @var ProductNumber $productNumber */
    private $productNumber;
    
    // ...
}

/**
 * Represents the translatable texts printed in a catalog.
 */
class ProductTranslation
{
    /** @var Language $title*/
    private $language;

    /** @var ProductTitle $title*/
    private $title;

    // ...
}

/**
 * Enforces business rules:
 *   - catalog texts are translatable only once in a language
 */
class ProductTranslationCollection
{
    /** @var ProductTranslation[] $translations*/
    private $translations;
}
```

#### 1. approach: ProductTranslationCollection is an aggregate root
* problem: ProductTranslationCollection has no table to specify in Entity::tableName()

```
$translations = $productTranslationRepository->load($product->getId()); // returns a ProductTranslationCollection

$translations->translate(
    new ProductTranslation(new Language('en'), new ProductTitle('Machinist Hammer'))
);

$productTranslationsRepository->save($translations);
```

#### 2. approach: translations are a sub-entity of the Product aggregate root
* problem: if a product is loaded all translations in all languages are loaded as well

```
$product = $productRepository->load($productId);

$product->translate(
    new ProductTranslation(new Language('en'), new ProductTitle('Machinist Hammer'))
);

$productRepository->save($product);
```

We discussed this in our team and would prefer approach 1. So TalisORM should support "collection aggregates". Or do we have a thinking error and this should be implemented quite differently?

**Comment by matthiasnoback** [comment]
Hi! Thanks for sharing your experience here. In this library, an aggregate root will always be a single identifiable object, with its own life cycle. However, that shouldn't be a problem for you, since there technically isn't any difference between example 1 and 2. You've only changed the names of the variables. In terms of implementation, you can choose to store the list of translations in a simple array and serialize it into a single column, or define child entities for every translation.
Indeed, TalisORM is never lazy-loading, and really, I don't think it will be a problem for you here. You will need the whole list of translations anyway, to decide if the translation you're adding is unique. Plus, it's going to be loaded only when you're doing a write operation. In most applications, the more common case is a read operation, and I don't recommend using an aggregate for reading information from. Instead, you should use a dedicated read model for that.

I hope this helps!

**Comment by pl-github** [comment]
Hi Matthias,

thank you very much for your quick answer. You're right, the two alternatives are very similar. Loading all data is really not important if the model is only used for writing.

After all these years of "Do everything with your Doctrine Entity" it's sometimes hard to change the mind towards DDD. 😄

**Comment by matthiasnoback** [comment]
Totally relatable :) You're welcome.
